## Travis CI configuration for the py++ library.
##
##   <https://travis-ci.org/mdklatt/pypp>
##
language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - main
    - dev

sudo: false

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build .
  
script:
  - test/unit/test_pypp
