## Travis CI configuration for the py++ library.
##
##   <https://travis-ci.org/mdklatt/pypp>
##
language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - main
    - dev

sudo: false

env:
  - PYPP_BUILD_TYPE="Debug" PYPP_BUILD_DIR="${TRAVIS_BUILD_DIR}/.build/${PYPP_BUILD_TYPE}"
  - PYPP_BUILD_TYPE="Release" PYPP_BUILD_DIR="${TRAVIS_BUILD_DIR}/.build/${PYPP_BUILD_TYPE}"

before_script:
  - mkdir -p "${PYPP_BUILD_DIR}"
  - cd "${PYPP_BUILD_DIR}"
  - cmake -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" -DPYPP_BUILD_TESTS=ON -DPYPP_BUILD_DOCS=ON "${TRAVIS_BUILD_DIR}"
  - cmake --build .
  - cd "${TRAVIS_BUILD_DIR}"
  
script:
  - ${PYPP_BUILD_DIR}/test/unit/test_pypp
  - cd test/integration && sh test.sh
