name: Build

on:
  push:
    branches:
      - main
      - dev

env:
  BUILD_TYPE: Release

jobs:
  build:
    # TODO: Test on Windows
    # TODO: Test with GCC and Clang
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: >
          cmake -S . -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DPYPP_BUILD_UNIT_TESTS=ON 
          -DPYPP_BUILD_CMAKE_TESTS=ON

      - name: Build project
        run: cmake --build ${{ github.workspace }}/build

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest
